spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ecommerce_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ecommerce_pass}

spring.h2.console.enabled=false
spring.cache.type=${SPRING_CACHE_TYPE:redis}
management.health.redis.enabled=${MANAGEMENT_HEALTH_REDIS_ENABLED:true}
app.inventory.lock.type=${APP_INVENTORY_LOCK_TYPE:redis}
